import {beforeAll,afterAll,describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {createUser,createWorkspace,createChannel,addMember,q,admin,expectDenied,pool,type TestUser} from '../helpers/db.ts';
let alice:TestUser,bob:TestUser,outsider:TestUser;let ws:string,foreign:string,channel:string,doc:string,company:string;
beforeAll(async()=>{alice=await createUser('connected-alice');bob=await createUser('connected-bob');outsider=await createUser('connected-outsider');ws=await createWorkspace(alice);foreign=await createWorkspace(outsider);await addMember(ws,bob);channel=await createChannel(alice,ws,{members:[bob]});doc=(await q(alice,"SELECT (drive_create_document($1,NULL,'Private policy','Travel budget: EUR 180')).id AS id",[ws]))[0].id;});
afterAll(()=>pool.end());
describe('connected Drive messages',()=>{
 it('requires explicit audience expansion and rolls back the whole post on failure',async()=>{const key=randomUUID();await expectDenied(q(alice,"SELECT send_drive_message($1,NULL,'policy',ARRAY[$2]::uuid[],false,$3)",[channel,doc,key]),/access|cannot|sharing/i);expect(await q(alice,"SELECT id FROM messages WHERE channel_id=$1 AND content='policy'",[channel])).toHaveLength(0);});
 it('shares the same resource atomically and concurrent retries produce one message',async()=>{const key=randomUUID();const calls=await Promise.all([q(alice,"SELECT send_drive_message($1,NULL,'policy',ARRAY[$2]::uuid[],true,$3) AS id",[channel,doc,key]),q(alice,"SELECT send_drive_message($1,NULL,'policy',ARRAY[$2]::uuid[],true,$3) AS id",[channel,doc,key])]);expect(calls[0][0].id).toBe(calls[1][0].id);expect(await q(bob,'SELECT id FROM drive_items WHERE id=$1',[doc])).toHaveLength(1);expect(await admin('SELECT id FROM message_resources WHERE message_id=$1',[calls[0][0].id])).toHaveLength(1);});
 it('rejects foreign resources even when grant is requested',async()=>{const other=(await q(outsider,"SELECT (drive_create_document($1,NULL,'foreign','secret')).id AS id",[foreign]))[0].id;await expectDenied(q(alice,"SELECT send_drive_message($1,NULL,'bad',ARRAY[$2]::uuid[],true,$3)",[channel,other,randomUUID()]));});
 it('dashboard does not expose another workspace or private resources',async()=>{expect((await q(bob,'SELECT workspace_dashboard($1) AS data',[foreign]))[0].data).toBeNull();expect(await q(outsider,'SELECT id FROM drive_items WHERE id=$1',[doc])).toHaveLength(0);});
});
describe('CRM tenant boundaries and activity',()=>{
 it('creates a company, contact, pipeline and deal with persisted stage activity',async()=>{company=(await q(alice,"INSERT INTO crm_companies(workspace_id,name,owner_id,created_by) VALUES($1,'Acme',$2,$2) RETURNING id",[ws,alice.id]))[0].id;const contact=(await q(alice,"INSERT INTO crm_contacts(workspace_id,name,email,company_id,owner_id,created_by) VALUES($1,'Sam','sam@example.test',$2,$3,$3) RETURNING id",[ws,company,alice.id]))[0].id;const pipeline=(await q(alice,"SELECT crm_create_pipeline($1,'Sales') AS id",[ws]))[0].id;const stages=await q(alice,'SELECT id FROM crm_stages WHERE pipeline_id=$1 ORDER BY position',[pipeline]);const deal=(await q(alice,"INSERT INTO crm_deals(workspace_id,name,company_id,contact_id,pipeline_id,stage_id,value,currency,owner_id,created_by) VALUES($1,'Launch',$2,$3,$4,$5,1500,'EUR',$6,$6) RETURNING id",[ws,company,contact,pipeline,stages[0].id,alice.id]))[0].id;await q(alice,'UPDATE crm_deals SET stage_id=$2 WHERE id=$1',[deal,stages[1].id]);expect(await q(bob,'SELECT id FROM crm_activity WHERE record_id=$1',[deal])).toHaveLength(2);expect(await q(outsider,'SELECT id FROM crm_deals WHERE id=$1',[deal])).toHaveLength(0);});
 it('prevents cross-workspace associations and tenant reassignment',async()=>{await expectDenied(q(outsider,"INSERT INTO crm_contacts(workspace_id,name,company_id,owner_id,created_by) VALUES($1,'bad',$2,$3,$3)",[foreign,company,outsider.id]),/foreign key|violates/);await expectDenied(q(alice,'UPDATE crm_companies SET workspace_id=$2 WHERE id=$1',[company,foreign]),/Immutable|member/);});
 it('does not let a member edit records owned by others',async()=>{expect(await q(bob,"UPDATE crm_companies SET name='stolen' WHERE id=$1 RETURNING id",[company])).toHaveLength(0);});
 it('filters restricted file associations and revokes them immediately',async()=>{const privateDoc=(await q(alice,"SELECT (drive_create_document($1,NULL,'Restricted appendix','private')).id AS id",[ws]))[0].id;await q(alice,'INSERT INTO crm_links(workspace_id,company_id,item_id,created_by) VALUES($1,$2,$3,$4)',[ws,company,privateDoc,alice.id]);expect(await q(bob,'SELECT id FROM crm_links WHERE company_id=$1',[company])).toHaveLength(0);});
 it('member removal remains possible after CRM ownership and stops all reads',async()=>{await q(bob,"INSERT INTO crm_companies(workspace_id,name,owner_id,created_by) VALUES($1,'Owned by Bob',$2,$2)",[ws,bob.id]);await q(alice,'SELECT remove_workspace_member($1,$2,$3)',[ws,bob.id,alice.id]);expect(await q(bob,'SELECT id FROM crm_companies WHERE workspace_id=$1',[ws])).toHaveLength(0);});
});
