import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { useWorkspaceContext } from '@/app/providers/WorkspaceProvider';
import { useAuth } from '@/hooks/useAuth';
import { useProfileContext } from '@/app/providers/ProfileProvider';
import { platform,result,api,errorText } from '@/features/platform/client';
import s from '@/features/platform/Platform.module.css';
interface Dashboard{tasks:number;projects:number;members:number;approvals:number;notifications:number;recent_files:Array<{id:string;name:string;kind:string}>;conversations:Array<{id:string;title:string}>;recent_tasks:Array<{id:string;title:string;status:string}>}
export function Home(){
 const {currentWorkspace}=useWorkspaceContext();const {userId}=useAuth();const {profile}=useProfileContext();const ws=currentWorkspace!.id;
 const data=useQuery({queryKey:['platform',ws,userId,'dashboard'],queryFn:async()=>await result(platform.rpc('workspace_dashboard',{p_workspace_id:ws})) as unknown as Dashboard,staleTime:10000,refetchInterval:30000});
 const agents=useQuery({queryKey:['platform',ws,userId,'agents','directory'],queryFn:()=>result(platform.rpc('agent_directory',{p_workspace_id:ws})),staleTime:10000});
 const status=useQuery({queryKey:['platform',ws,userId,'home-ai-status'],queryFn:async()=>await(await api(`ai/status?workspace_id=${ws}`)).json() as {provider:{configured:boolean}},retry:false,staleTime:30000});
 return <div className={s.page}><header className={s.header}><div><div className={s.eyebrow}>{currentWorkspace!.name} · Overview</div><h1>Good to see you, {profile?.display_name?.split(' ')[0]||profile?.username||'teammate'}.</h1><p className={s.muted}>Your team, your knowledge, your next step.</p></div><div className={s.actions}><Link className={s.button} to="/channels">Open chat</Link><Link className={s.primary} to="/drive">Upload or create a file</Link></div></header>
 {data.error&&<p role="alert" className={s.error}>{errorText(data.error)} <button onClick={()=>void data.refetch()}>Retry</button></p>}
 <div className={s.stats}>{[['Unread activity',data.data?.notifications,'/notifications'],['Actions to review',data.data?.approvals,'/agents'],['Accessible tasks',data.data?.tasks,'/tasks'],['Active projects',data.data?.projects,'/projects']].map(([label,count,url])=><Link className={`${s.card} ${s.link}`} to={String(url)} key={label}><div className={s.eyebrow}>{label}</div><strong style={{fontSize:30}}>{data.isPending?'…':count??'—'}</strong><span className={s.muted}> ↗</span></Link>)}</div>
 <h2 className={s.section}>Your AI team</h2><p className={s.muted}>{status.data?.provider.configured?'Specialists working with the sources you can access.':'Explore your specialists. Connect an AI provider in server configuration to start using them.'}</p><div className={s.grid}>{agents.data?.slice(0,4).map(a=><article className={s.card} key={a.id}><div className={s.badge} style={{borderBottom:`3px solid ${a.color}`}}>{a.name[0]}</div><h2>{a.name}</h2><p>{a.capability}</p><Link className={s.button} to={`/agents/${a.id}`}>Open agent →</Link></article>)}</div><p><Link className={s.link} to="/agents">Meet all specialists →</Link></p>
 <div className={s.split}><section><h2 className={s.section}>Continue work</h2><div className={s.stack}>{data.data?.conversations.map(c=><Link key={c.id} className={`${s.card} ${s.link}`} to={`/agents/conversations/${c.id}`}>✦ {c.title}<p className={s.muted}>Private agent conversation</p></Link>)}{data.data?.recent_files.map(f=><Link key={f.id} className={`${s.card} ${s.link}`} to={`/drive/${f.kind==='folder'?'folder':'item'}/${f.id}`}>▤ {f.name}<p className={s.muted}>Recently opened</p></Link>)}{!data.data?.recent_files.length&&!data.data?.conversations.length&&<div className={s.empty}>Files you open and conversations you start will appear here.</div>}</div></section><section><h2 className={s.section}>Recent tasks</h2><div className={s.stack}>{data.data?.recent_tasks.map(t=><Link key={t.id} className={`${s.card} ${s.link}`} to={`/tasks/${t.id}`}>{t.title}<p className={s.muted}>{t.status}</p></Link>)}{!data.data?.recent_tasks.length&&<div className={s.empty}><p>Start with a task for your team.</p><Link to="/tasks">Create a task</Link></div>}</div></section></div>
 <section className={s.notice} style={{marginTop:28}}><strong>Build your shared workspace</strong><p>{data.data?.members??'—'} workspace members. Invite a teammate, create a channel, and share your first document.</p><div className={s.actions}><Link className={s.button} to="/settings">Workspace settings</Link><Link className={s.button} to="/channels">Create a channel</Link><Link className={s.button} to="/drive">Open Drive</Link></div></section></div>;
}
