import { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { useWorkspaceContext } from '@/app/providers/WorkspaceProvider';
import { useAuth } from '@/hooks/useAuth';
import { Dialog } from '@/components/ui/Dialog';
import { platform,result,errorText,api } from './client';
import s from './Platform.module.css';

export function DriveShare({channelId,parentId}:{channelId:string;parentId?:string}){
 const {currentWorkspace}=useWorkspaceContext();const {userId}=useAuth();const [open,setOpen]=useState(false);const [selected,setSelected]=useState<string[]>([]);const [caption,setCaption]=useState('');const [grant,setGrant]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const key=useRef(crypto.randomUUID());
 const files=useQuery({queryKey:['platform',currentWorkspace?.id,userId,'drive-picker'],enabled:open&&!!currentWorkspace,queryFn:()=>result(platform.rpc('drive_list',{p_workspace_id:currentWorkspace!.id,p_view:'all',p_limit:100}))});
 const gap=useQuery({queryKey:['platform',currentWorkspace?.id,userId,'drive-gap',channelId,selected],enabled:open&&!!selected.length,queryFn:async()=>await result(platform.rpc('drive_conversation_access_check',{p_channel_id:channelId,p_item_ids:selected})) as Array<{item_id:string;members_without_access:number;can_grant:boolean}>});
 const gaps=gap.data?.filter(g=>g.members_without_access>0)??[];
 return <><button type="button" className={s.button} onClick={()=>setOpen(true)}>Share from Drive</button><Dialog open={open} onClose={()=>setOpen(false)} title="Share files in this conversation"><form className={s.form} onSubmit={e=>{e.preventDefault();setBusy(true);setError('');void result(platform.rpc('send_drive_message',{p_channel_id:channelId,p_parent_id:parentId??null,p_content:caption,p_item_ids:selected,p_grant_channel:grant,p_request_id:key.current})).then(async id=>{window.dispatchEvent(new CustomEvent('drive-message-sent',{detail:{channelId,parentId}}));if(caption.includes('@'))void api('agents/mention',{message_id:id}).catch(()=>{});setOpen(false);setSelected([]);setCaption('');setGrant(false);key.current=crypto.randomUUID();}).catch(e=>setError(errorText(e))).finally(()=>setBusy(false));}}><p className={s.muted}>References the existing file and its current version. No new upload is created.</p>{files.data?.filter(f=>f.kind!=='folder').map(f=><label key={f.id} style={{display:'flex'}}><input type="checkbox" checked={selected.includes(f.id)} onChange={e=>{setSelected(v=>e.target.checked?[...v,f.id].slice(0,20):v.filter(id=>id!==f.id));setGrant(false);key.current=crypto.randomUUID();}}/>{f.name}</label>)}{gaps.length>0&&<div className={s.notice}>Some members cannot open {gaps.length} selected file(s).{gaps.every(g=>g.can_grant)?<label><input type="checkbox" checked={grant} onChange={e=>setGrant(e.target.checked)}/>Grant viewer access to this conversation’s current and future members</label>:<p>Ask the owner to grant this conversation access before sharing.</p>}</div>}<label>Message<textarea className={s.text} value={caption} onChange={e=>{setCaption(e.target.value);key.current=crypto.randomUUID();}}/></label>{(error||files.error||gap.error)&&<p role="alert" className={s.error}>{error||errorText(files.error??gap.error)}</p>}<button className={s.primary} disabled={busy||!selected.length||gap.isPending||!!gap.error||(gaps.length>0&&(!grant||!gaps.every(g=>g.can_grant)))}>Share selected files</button></form></Dialog></>;
}
export function MessageResources({messageId,workspaceId}:{messageId:string;workspaceId:string|null}){
 const {userId}=useAuth();const files=useQuery({queryKey:['platform',workspaceId,userId,'message-resources',messageId],staleTime:0,refetchInterval:30000,queryFn:async()=>{const refs=await result(platform.from('message_resources').select('*').eq('message_id',messageId));if(!refs.length)return[];const items=await result(platform.from('drive_items').select('id,name').in('id',refs.map(r=>r.item_id)));return refs.map(r=>({...r,name:items.find(i=>i.id===r.item_id)?.name}));}});
 return <div className={s.actions}>{files.data?.map(f=><Link className={s.button} key={f.id} to={`/drive/item/${f.item_id}${f.version_id?`?version=${f.version_id}`:''}`}>▤ {f.name??'File unavailable'}</Link>)}</div>;
}
