/**
 * Local Supabase emulation (PostgreSQL 17 + PostgREST + gateway) for development
 * and tests. Usage:
 *
 *   npm run supabase:local -- start     # init on first run, start all services, apply migrations
 *   npm run supabase:local -- migrate   # apply new migrations
 *   npm run supabase:local -- status
 *   npm run supabase:local -- stop
 *   npm run supabase:local -- reset     # destroy local data and start fresh
 *
 * State lives in .local/supabase (git-ignored). Never point this at a hosted project.
 */
import { spawn, spawnSync } from 'node:child_process';
import { existsSync, openSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import {
  DATABASE_URL,
  ENV_FILE,
  GATEWAY_PORT,
  GATEWAY_URL,
  JWKS_FILE,
  LOG_DIR,
  PGDATA,
  PG_BIN,
  PG_PORT,
  PIDS_FILE,
  POSTGREST_BIN,
  POSTGREST_CONF,
  POSTGREST_PORT,
  REPO_ROOT,
  STATE_DIR,
  applyMigrations,
  ensureDir,
  loadOrCreateKeys,
  psql,
} from './lib.ts';

interface Pids {
  postgrest?: number;
  gateway?: number;
}

function readPids(): Pids {
  return existsSync(PIDS_FILE) ? (JSON.parse(readFileSync(PIDS_FILE, 'utf8')) as Pids) : {};
}

function isAlive(pid?: number): boolean {
  if (!pid) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

function pgIsRunning(): boolean {
  const r = spawnSync(path.join(PG_BIN, 'pg_ctl'), ['-D', PGDATA, 'status'], { encoding: 'utf8' });
  return r.status === 0;
}

async function waitFor(check: () => Promise<boolean> | boolean, label: string, timeoutMs = 15000): Promise<void> {
  const started = Date.now();
  while (Date.now() - started < timeoutMs) {
    if (await check()) return;
    await new Promise((r) => setTimeout(r, 200));
  }
  throw new Error(`Timed out waiting for ${label}`);
}

async function httpOk(url: string): Promise<boolean> {
  try {
    const res = await fetch(url);
    return res.status < 500;
  } catch {
    return false;
  }
}

function initCluster(): void {
  ensureDir(STATE_DIR);
  ensureDir(LOG_DIR);
  if (existsSync(path.join(PGDATA, 'PG_VERSION'))) return;
  const r = spawnSync(
    path.join(PG_BIN, 'initdb'),
    ['-D', PGDATA, '-U', 'postgres', '--auth=trust', '--encoding=UTF8', '--locale=C'],
    { encoding: 'utf8' },
  );
  if (r.status !== 0) throw new Error(`initdb failed: ${r.stderr}`);
}

function startPostgres(): void {
  if (pgIsRunning()) return;
  const r = spawnSync(
    path.join(PG_BIN, 'pg_ctl'),
    [
      '-D',
      PGDATA,
      '-l',
      path.join(LOG_DIR, 'postgres.log'),
      '-w',
      '-o',
      `-p ${PG_PORT} -c listen_addresses=localhost -c unix_socket_directories= -c wal_level=logical -c max_connections=200`,
      'start',
    ],
    { encoding: 'utf8' },
  );
  if (r.status !== 0) throw new Error(`pg_ctl start failed: ${r.stderr || r.stdout}`);
}

async function writePostgrestConfig(): Promise<void> {
  await loadOrCreateKeys();
  const conf = [
    `db-uri = "postgres://authenticator:authenticator-local-only@localhost:${PG_PORT}/postgres"`,
    'db-schemas = "public"',
    'db-anon-role = "anon"',
    'db-extra-search-path = "public, extensions"',
    'db-max-rows = 1000',
    'db-pool = 20',
    `server-port = ${POSTGREST_PORT}`,
    'server-host = "localhost"',
    `jwt-secret = "@${JWKS_FILE}"`,
    'log-level = "warn"',
  ].join('\n');
  writeFileSync(POSTGREST_CONF, `${conf}\n`);
}

function spawnDetached(command: string, args: string[], logName: string, env: NodeJS.ProcessEnv = {}): number {
  const out = openSync(path.join(LOG_DIR, `${logName}.log`), 'a');
  const child = spawn(command, args, {
    cwd: REPO_ROOT,
    detached: true,
    stdio: ['ignore', out, out],
    env: { ...process.env, ...env },
  });
  child.unref();
  return child.pid ?? 0;
}

async function writeEnvFile(): Promise<void> {
  const keys = await loadOrCreateKeys();
  const lines = [
    '# Generated by tools/local-supabase. Local development only.',
    `VITE_SUPABASE_URL=${GATEWAY_URL}`,
    `VITE_SUPABASE_ANON_KEY=${keys.anonKey}`,
    `SUPABASE_URL=${GATEWAY_URL}`,
    `SUPABASE_SECRET_KEY=${keys.serviceKey}`,
    `LOCAL_DATABASE_URL=${DATABASE_URL}`,
  ];
  writeFileSync(ENV_FILE, `${lines.join('\n')}\n`, { mode: 0o600 });
}

async function start(): Promise<void> {
  initCluster();
  startPostgres();
  const applied = applyMigrations();
  if (applied.length) console.log(`Applied migrations:\n  ${applied.join('\n  ')}`);
  psql(['-c', "NOTIFY pgrst, 'reload schema'"]);
  await writePostgrestConfig();
  await writeEnvFile();
  const pids = readPids();
  if (!isAlive(pids.postgrest)) {
    pids.postgrest = spawnDetached(POSTGREST_BIN, [POSTGREST_CONF], 'postgrest');
  }
  await waitFor(() => httpOk(`http://localhost:${POSTGREST_PORT}/`), 'PostgREST');
  if (!isAlive(pids.gateway)) {
    pids.gateway = spawnDetached(
      path.join(REPO_ROOT, 'node_modules', '.bin', 'tsx'),
      [path.join(REPO_ROOT, 'tools', 'local-supabase', 'gateway.ts')],
      'gateway',
    );
  }
  writeFileSync(PIDS_FILE, JSON.stringify(pids));
  await waitFor(() => httpOk(`${GATEWAY_URL}/health`), 'gateway');
  console.log(`Local Supabase ready:
  API gateway   ${GATEWAY_URL}
  PostgREST     http://localhost:${POSTGREST_PORT}
  Postgres      ${DATABASE_URL}
  Env file      ${ENV_FILE}`);
}

function stop(): void {
  const pids = readPids();
  for (const pid of [pids.gateway, pids.postgrest]) {
    if (isAlive(pid)) process.kill(pid!, 'SIGTERM');
  }
  if (pgIsRunning()) {
    spawnSync(path.join(PG_BIN, 'pg_ctl'), ['-D', PGDATA, '-m', 'fast', 'stop'], { encoding: 'utf8' });
  }
  rmSync(PIDS_FILE, { force: true });
  console.log('Local Supabase stopped.');
}

async function status(): Promise<void> {
  const pids = readPids();
  console.log(`postgres   ${pgIsRunning() ? 'running' : 'stopped'} (port ${PG_PORT})`);
  console.log(`postgrest  ${isAlive(pids.postgrest) ? 'running' : 'stopped'} (port ${POSTGREST_PORT})`);
  console.log(`gateway    ${isAlive(pids.gateway) ? 'running' : 'stopped'} (port ${GATEWAY_PORT})`);
}

const command = process.argv[2] ?? 'status';
switch (command) {
  case 'start':
    await start();
    break;
  case 'stop':
    stop();
    break;
  case 'migrate': {
    const applied = applyMigrations();
    psql(['-c', "NOTIFY pgrst, 'reload schema'"]);
    console.log(applied.length ? `Applied:\n  ${applied.join('\n  ')}` : 'No new migrations.');
    break;
  }
  case 'reset':
    stop();
    rmSync(STATE_DIR, { recursive: true, force: true });
    await start();
    break;
  case 'status':
    await status();
    break;
  default:
    console.error(`Unknown command: ${command}`);
    process.exit(1);
}
