import { parseCsv } from '../../../../shared/csv';
import { useEffect, useState, useMemo, useCallback } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Dialog } from '@/components/ui/Dialog';
import { platform, result, api, errorText, workspacePeople, type Row } from '@/features/platform/client';
import s from '@/features/platform/Platform.module.css';

interface Access { my_role:string;can_manage:boolean;audience_count:number;grants:Array<{id:string;label:string;role:string;inherited:boolean;via_name:string;principal_type:string}> }
export function DriveItem({itemId,workspaceId:ws,userId}:{itemId:string;workspaceId:string;userId:string}) {
  const cache=useQueryClient();const navigate=useNavigate();const [params]=useSearchParams();
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [sharing,setSharing]=useState(params.get('panel')==='sharing');
  const [rename,setRename]=useState(false);const [name,setName]=useState('');
  const [target,setTarget]=useState('workspace');const [role,setRole]=useState('viewer');
  const [move,setMove]=useState(false);const [folder,setFolder]=useState('');const [movePreview,setMovePreview]=useState<{gains:Array<{type:string;id:string|null}>;losses:Array<{type:string;id:string|null}>}|null>(null);
  const [comment,setComment]=useState('');const [requested,setRequested]=useState(false);
  const base=['platform',ws,userId,'item',itemId];
  const item=useQuery({queryKey:base,queryFn:()=>result(platform.from('drive_items').select('*').eq('workspace_id',ws).eq('id',itemId).maybeSingle()),staleTime:0,refetchInterval:15000});
  const detail=useQuery({queryKey:[...base,'details',params.get('revision')],enabled:!!item.data&&!item.data.trashed_at,refetchInterval:15000,queryFn:async()=>{
    const [access,revisions,versions,comments,sources,requests]=await Promise.all([
      result(platform.rpc('drive_get_access',{p_item_id:itemId})),
      result(params.get('revision') ? platform.from('drive_document_revisions').select('*').eq('item_id',itemId).eq('id',params.get('revision')!) : platform.from('drive_document_revisions').select('*').eq('item_id',itemId).order('revision_no',{ascending:false}).limit(25)),
      result(platform.from('drive_versions').select('*').eq('item_id',itemId).eq('status','ready').order('version_no',{ascending:false}).limit(25)),
      result(platform.from('drive_comments').select('*').eq('item_id',itemId).is('deleted_at',null).order('created_at').limit(100)),
      result(platform.from('knowledge_sources').select('*').eq('item_id',itemId).is('superseded_at',null)),
      result(platform.from('drive_access_requests').select('*').eq('item_id',itemId).eq('status','pending')),
    ]);return {access:access as unknown as Access,revisions,versions,comments,sources,requests};
  }});
  const options=useQuery({queryKey:['platform',ws,userId,'share-options'],enabled:sharing||move,queryFn:async()=>{
    const [members,channels,projects,folders]=await Promise.all([
      workspacePeople(ws),
      result(platform.from('channels').select('id,name').eq('workspace_id',ws).order('name')),
      result(platform.from('projects').select('id,name').eq('workspace_id',ws)),
      result(platform.rpc('drive_list',{p_workspace_id:ws,p_view:'all',p_limit:500})),
    ]);return{members,channels,projects,folders:folders.filter(f=>f.kind==='folder'&&f.id!==itemId)};
  }});
  const refresh=()=>cache.invalidateQueries({queryKey:['platform',ws,userId]});
  async function act(fn:()=>PromiseLike<unknown>){setBusy(true);setError('');try{await fn();await refresh();return true;}catch(e){setError(errorText(e));return false;}finally{setBusy(false);}}
  useEffect(()=>{void platform.rpc('drive_record_view',{p_item_id:itemId});},[itemId]);
  if(item.isPending)return <div className={s.page}>Loading file…</div>;
  if(!item.data||item.data.trashed_at)return <div className={s.page}><Link to="/drive">← Drive</Link><div className={s.empty}><h1>File unavailable</h1><p>This link may require access, or the file may have been removed.</p>{item.error&&<p>{errorText(item.error)}</p>}<button className={s.button} disabled={requested||busy} onClick={()=>void act(async()=>{await result(platform.rpc('drive_request_access',{p_item_id:itemId}));setRequested(true);})}>{requested?'Access request submitted':'Request access'}</button></div></div>;
  const d=item.data;const access=detail.data?.access;const editable=access?.my_role==='owner'||access?.my_role==='editor';
  return <div className={s.page}>
    <header className={s.header}><div><Link className={s.muted} to={d.parent_id?`/drive/folder/${d.parent_id}`:'/drive?view=my'}>← Back to Drive</Link><h1>{d.name}</h1><span className={s.muted}>{d.kind} · Updated {new Date(d.updated_at).toLocaleString()}</span></div><div className={s.actions}>
      <Link className={s.button} to={`/agents?source=${itemId}`}>Ask an agent</Link><button className={s.button} onClick={()=>void act(()=>navigator.clipboard.writeText(`${location.origin}/drive/item/${itemId}`))}>Copy link</button><button className={s.primary} onClick={()=>setSharing(true)}>Sharing</button>
      {editable&&<><button className={s.button} onClick={()=>{setName(d.name);setRename(true);}}>Rename</button><button className={s.button} onClick={()=>setMove(true)}>Move</button><button className={s.button} onClick={()=>void act(async()=>{await result(platform.rpc('drive_trash',{p_item_id:itemId}));navigate('/drive?view=trash');})}>Move to Trash</button></>}
    </div></header>
    {(error||detail.error)&&<p role="alert" className={s.error}>{error||errorText(detail.error)}</p>}
    <div className={s.split}><div className={s.stack}>
      {d.kind==='document'&&detail.data?.revisions[0]?<DocumentEditor key={params.get('revision')??'current'} item={d} revision={detail.data.revisions[0]} editable={editable&&!params.get('revision')} onSaved={refresh}/>:d.kind==='file'?<FilePreview item={d} versions={detail.data?.versions ?? []}/>:d.kind==='folder'?<Link to={`/drive/folder/${itemId}`}>Open folder</Link>:<p className={s.muted}>{detail.isPending?'Loading document…':'This revision is unavailable.'}</p>}
      <section className={s.card}><h2>Comments</h2>{detail.data?.comments.map(c=><div className={s.message} key={c.id}><div className={s.muted}>{c.author_id===userId?'You':'Workspace member'} · {new Date(c.created_at).toLocaleString()}</div>{c.body}</div>)}{['owner','editor','commenter'].includes(access?.my_role ?? '')&&<form className={s.form} onSubmit={e=>{e.preventDefault();void act(async()=>{await result(platform.rpc('drive_add_comment',{p_item_id:itemId,p_body:comment}));setComment('');});}}><label>Add a comment<textarea className={s.text} value={comment} onChange={e=>setComment(e.target.value)} required maxLength={10000}/></label><button className={s.button} disabled={busy}>Post comment</button></form>}</section>
    </div><aside className={s.stack}><section className={s.card}><div className={s.eyebrow}>Details</div><p>Your access: <strong>{access?.my_role ?? 'Checking…'}</strong></p><p className={s.muted}>{access?.audience_count ?? '—'} people can open this file.</p><p className={s.muted}>Copying the link does not grant access.</p></section>
      <section className={s.card}><h2>Knowledge status</h2>{!detail.data?.sources.length&&<p className={s.muted}>Waiting for indexing.</p>}{detail.data?.sources.map(k=><div key={k.id}><span className={s.pill}>{k.status}</span><p className={s.muted}>{k.error_message ?? 'Extraction runs separately from uploading.'}</p></div>)}<button className={s.button} onClick={()=>void act(()=>api('jobs/run',{workspace_id:ws}))}>Process pending work</button>{editable&&<button className={s.button} onClick={()=>void act(async()=>{await result(platform.rpc('knowledge_reindex_item',{p_item_id:itemId}));await api('jobs/run',{workspace_id:ws});})}>Reindex</button>}</section>
      <section className={s.card}><h2>Version history</h2>{detail.data?.revisions.map(r=><details key={r.id}><summary className={s.muted}>Revision {r.revision_no} · {new Date(r.created_at).toLocaleString()}</summary><pre className={s.prose}>{r.body}</pre></details>)}{detail.data?.versions.map(v=><p key={v.id} className={s.muted}>Version {v.version_no} · {v.original_name}<br/>{new Date(v.created_at).toLocaleString()}</p>)}</section>
    </aside></div>
    <Dialog open={rename} onClose={()=>setRename(false)} title="Rename"><form className={s.form} onSubmit={e=>{e.preventDefault();void act(async()=>{await result(platform.rpc('drive_rename',{p_item_id:itemId,p_name:name}));setRename(false);});}}><label>Name<input className={s.input} value={name} onChange={e=>setName(e.target.value)} required maxLength={255}/></label><button className={s.primary} disabled={busy}>Save name</button></form></Dialog>
    <Dialog open={sharing} onClose={()=>setSharing(false)} title="Sharing and access"><div className={s.form}><p className={s.muted}>Channel and project access follows current membership, including future joins and removals. A copied link grants no access.</p>{error&&<p role="alert" className={s.error}>{error}</p>}{access?.grants.map(g=><div key={g.id} className={s.actions}><span>{g.label} · {g.role}{g.inherited?` · inherited from ${g.via_name}`:''}</span>{access.can_manage&&!g.inherited&&<button className={s.button} onClick={()=>void act(()=>result(platform.rpc('drive_unshare',{p_grant_id:g.id})))}>Remove</button>}</div>)}{access?.can_manage&&<form className={s.form} onSubmit={e=>{e.preventDefault();const [kind,id]=target.split(':');void act(()=>result(platform.rpc('drive_share',{p_item_id:itemId,p_principal_type:kind,p_principal_id:id??null,p_role:role})));}}><label>Share with<select className={s.input} value={target} onChange={e=>setTarget(e.target.value)}><option value="workspace">Everyone in this workspace</option>{options.data?.members.map(m=><option key={m.id} value={`user:${m.id}`}>{m.display_name||m.username}</option>)}{options.data?.channels.map(c=><option key={c.id} value={`channel:${c.id}`}>Channel: {c.name}</option>)}{options.data?.projects.map(p=><option key={p.id} value={`project:${p.id}`}>Project: {p.name}</option>)}</select></label><label>Permission<select className={s.input} value={role} onChange={e=>setRole(e.target.value)}><option>viewer</option><option>commenter</option><option>editor</option></select></label><button className={s.primary} disabled={busy}>Grant {role} access</button></form>}{access?.can_manage&&detail.data?.requests.map(r=><div key={r.id} className={s.notice}>Pending access request · {r.role}<p>{r.message}</p><button className={s.button} onClick={()=>void act(()=>result(platform.rpc('drive_decide_access_request',{p_request_id:r.id,p_approve:true})))}>Approve</button> <button className={s.button} onClick={()=>void act(()=>result(platform.rpc('drive_decide_access_request',{p_request_id:r.id,p_approve:false})))}>Decline</button></div>)}</div></Dialog>
    <Dialog open={move} onClose={()=>setMove(false)} title="Move file"><div className={s.form}><label>Destination<select className={s.input} value={folder} onChange={e=>{setFolder(e.target.value);setMovePreview(null);}}><option value="">My files (root)</option>{options.data?.folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><button className={s.button} onClick={()=>void act(async()=>setMovePreview(await result(platform.rpc('drive_preview_move',{p_item_id:itemId,p_new_parent_id:folder||null})) as typeof movePreview))}>Preview access changes</button>{movePreview!==null&&<><div className={s.notice}>{(['gains','losses'] as const).map(kind=><p key={kind}>{kind==='gains'?'Gaining access':'Losing inherited access'}: {movePreview[kind].length ? movePreview[kind].map(g=>g.type==='workspace'?'Everyone in the workspace':g.type==='user'?options.data?.members.find(m=>m.id===g.id)?.display_name??'Workspace member':g.type==='channel'?`Channel: ${options.data?.channels.find(c=>c.id===g.id)?.name??'restricted channel'}`:`Project: ${options.data?.projects.find(p=>p.id===g.id)?.name??'restricted project'}`).join(', '):'No changes'}</p>)}</div><button className={s.primary} disabled={busy} onClick={()=>void act(async()=>{await result(platform.rpc('drive_move',{p_item_id:itemId,p_new_parent_id:folder||null}));setMove(false);})}>Confirm move</button></>}{error&&<p role="alert">{error}</p>}</div></Dialog>
  </div>;
}
function DocumentEditor({item,revision,editable,onSaved}:{item:Row<'drive_items'>;revision:Row<'drive_document_revisions'>;editable:boolean;onSaved:()=>Promise<unknown>}) {
  const [body,setBody]=useState(revision.body);const [savedBody,setSavedBody]=useState(revision.body);const [base,setBase]=useState(revision.revision_no);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  const state=saving?'Saving…':body===savedBody?'Saved':'Unsaved';
  const save=useCallback(async()=>{const submitted=body;setSaving(true);setError('');try{await result(platform.rpc('drive_save_document',{p_item_id:item.id,p_base_revision_no:base,p_title:item.name,p_body:submitted}));setBase(base+1);setSavedBody(submitted);await onSaved();void api('jobs/run',{workspace_id:item.workspace_id}).catch(()=>{});}catch(e){setError(errorText(e));}finally{setSaving(false);}},[body,base,item.id,item.name,item.workspace_id,onSaved]);
  useEffect(()=>{if(!editable||saving||body===savedBody||error)return;const timer=setTimeout(()=>void save(),1500);return()=>clearTimeout(timer);},[body,savedBody,saving,error,editable,save]);
  return <section className={s.preview}><div className={s.toolbar} style={{padding:'0 18px'}}><span className={s.muted}>{state} · Markdown document · Revision {base}</span>{editable&&<button className={s.button} disabled={state==='Saved'||state==='Saving…'} onClick={()=>void save()}>Save changes</button>}</div>{error&&<div className={s.error} role="alert">{error}<p>Your draft is preserved. Reload the latest revision or save your draft as a separate document.</p><button className={s.button} onClick={()=>{setBody(revision.body);setBase(revision.revision_no);setSavedBody(revision.body);setError('');}}>Load latest revision</button> <button className={s.button} onClick={()=>void result(platform.rpc('drive_create_document',{p_workspace_id:item.workspace_id,p_parent_id:item.parent_id,p_title:`${item.name} (copy)`,p_body:body})).then(d=>{location.assign(`/drive/item/${d.id}`);}).catch(e=>setError(errorText(e)))}>Save a copy</button></div>}<textarea aria-label="Document content" className={s.editor} value={body} readOnly={!editable} onChange={e=>{setBody(e.target.value);}}/></section>;
}
function FilePreview({item,versions}:{item:Row<'drive_items'>;versions:Row<'drive_versions'>[]}) {
  const [params]=useSearchParams();const [text,setText]=useState('');const [csvPage,setCsvPage]=useState(0);
  const v=versions.find(v=>v.id===(params.get('version')??item.current_version_id));
  const signed=useQuery({queryKey:['platform',item.workspace_id,'preview',item.id,v?.id],enabled:!!v,staleTime:0,gcTime:0,queryFn:()=>result(platform.storage.from(v!.storage_bucket).createSignedUrl(v!.storage_path,60))});
  const url=signed.data?.signedUrl;
  const mime=v?.mime_type ?? item.mime_type ?? '';
  useEffect(()=>{setText('');if(!url||!(/^(text\/(plain|markdown|csv))/.test(mime))||item.size_bytes>2_000_000)return;const abort=new AbortController();fetch(url,{signal:abort.signal}).then(r=>r.text()).then(t=>setText(t.slice(0,100000))).catch(()=>{});return()=>abort.abort();},[url,mime,item.size_bytes]);
  const csv=useMemo(()=>mime==='text/csv'&&text?parseCsv(text,1000):null,[mime,text]);
  return <section className={s.preview}>{signed.error&&<p className={s.error}>{errorText(signed.error)}</p>}{!url?<p className={s.prose}>Loading preview…</p>:<>{/^image\/(png|jpeg|gif|webp|avif)$/.test(mime)?<img src={url} alt={item.name}/>:mime==='application/pdf'?<iframe title={item.name} src={`${url}#page=${Number(params.get('page'))||1}`} sandbox="allow-same-origin"/>:csv?<><div className={s.tableWrap}><table className={s.table}><thead><tr>{csv.header.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{csv.rows.slice(csvPage*25,csvPage*25+25).map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div><div className={s.toolbar}><button className={s.button} disabled={!csvPage} onClick={()=>setCsvPage(csvPage-1)}>Previous rows</button><span>Rows {csvPage*25+1}–{Math.min(csv.rows.length,(csvPage+1)*25)} · Preview limited to 1,000 rows / 100,000 characters</span><button className={s.button} disabled={(csvPage+1)*25>=csv.rows.length} onClick={()=>setCsvPage(csvPage+1)}>Next rows</button></div></>:text?<pre className={s.prose}>{text}</pre>:<p className={s.prose}>Preview unavailable for this file. Download to open it in a compatible application.</p>}<div className={s.toolbar} style={{padding:'0 18px'}}><a className={s.button} href={url} download={item.name} target="_blank" rel="noopener noreferrer">Download original</a><button className={s.button} onClick={()=>void signed.refetch()}>Refresh download link</button></div></>}</section>;
}
